// <auto-generated />
using System;
using AM.TestTask.Data.Relational.AppDatabase.PostgreSql.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AM.TestTask.Data.Relational.AppDatabase.PostgreSql.Migrations
{
    [DbContext(typeof(ApplicationDatabaseContext))]
    [Migration("20251127004105_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AM.TestTask.Business.Entities.Meteorite", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("FallType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<decimal?>("Mass")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NameType")
                        .HasColumnType("integer");

                    b.Property<int>("RecClassId")
                        .HasColumnType("integer");

                    b.Property<short?>("Year")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Name"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Name"), new[] { "gin_trgm_ops" });

                    b.HasIndex("RecClassId");

                    b.HasIndex("Year", "RecClassId");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("Year", "RecClassId"), new[] { "Mass" });

                    b.ToTable("Meteorites");
                });

            modelBuilder.Entity("AM.TestTask.Business.Entities.RecClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RecClasses");
                });

            modelBuilder.Entity("AM.TestTask.Data.Relational.AppDatabase.PostgreSql.Models.MeteoriteStaging", b =>
                {
                    b.Property<int>("FallType")
                        .HasColumnType("integer");

                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<decimal?>("Mass")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NameType")
                        .HasColumnType("integer");

                    b.Property<string>("RecClassRaw")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<short?>("Year")
                        .HasColumnType("smallint");

                    b.ToTable("MeteoriteStaging_Fake", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("AM.TestTask.Business.Entities.Meteorite", b =>
                {
                    b.HasOne("AM.TestTask.Business.Entities.RecClass", "RecClass")
                        .WithMany()
                        .HasForeignKey("RecClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecClass");
                });
#pragma warning restore 612, 618
        }
    }
}
